#!/usr/bin/php
<?php

  $conf = './app/environment.json';

  if( !file_exists( $conf ) ) {
    // Environment file not found.
    exit("
  ⚠️  No environment settings was found!
  ➡️  Create a new /app/environment.json file manually.
  🔗  Details: https://getzincphp.github.io/docs/Alpha/Configuration/index.html
    \n");
  }

  // Environment file was found!
  // Check if we have the container name.
  $conf = json_decode( file_get_contents( $conf ), true );
  // Get docker container name.
  $container = false;
  if(isset($conf['cli']['container_name'])) {
    if(!empty($conf['cli']['container_name'])) {
      $container = $conf['cli']['container_name'];
    }
  }
  // Check if valid container name was given.
  if(!$container) {
    exit("️⚠️  Add docker container name in '/app/environment.json'\n");
  }
  array_shift( $argv );
  // $command = 'docker run --rm -v $(pwd):/app -w /app '.$container.' php zinc ' . implode(' ', $argv );
  $command = 'docker exec -i ' . $container . ' php zinc ' . implode(' ', $argv );
  echo passthru( $command );